// Singapore locations for artisan profiles
export const SINGAPORE_LOCATIONS = [
  "Admiralty",
  "Ang Mo Kio",
  "Bedok",
  "Bishan",
  "Boon Lay",
  "Braddell",
  "Bukit Batok",
  "Bukit Gombak",
  "Bukit Merah",
  "Bukit Panjang",
  "Bukit Timah",
  "Bugis",
  "Changi",
  "Chinatown",
  "City Hall",
  "Clarke Quay",
  "Clementi",
  "Commonwealth",
  "Dhoby Ghaut",
  "Dover",
  "Eunos",
  "Geylang",
  "Hillview",
  "Holland Village",
  "Hougang",
  "Jurong East",
  "Jurong West",
  "Katong",
  "Khatib",
  "Kovan",
  "Mandai",
  "Marine Parade",
  "Marina Bay",
  "Novena",
  "Orchard",
  "Outram Park",
  "Pasir Panjang",
  "Pasir Ris",
  "Paya Lebar",
  "Pioneer",
  "Punggol",
  "Queenstown",
  "Raffles Place",
  "Redhill",
  "River Valley",
  "Sembawang",
  "Seletar",
  "Sengkang",
  "Serangoon",
  "Siglap",
  "Tampines",
  "Tanglin",
  "Tanjong Pagar",
  "Telok Blangah",
  "Thomson",
  "Toa Payoh",
  "Tuas",
  "West Coast",
  "Woodlands",
  "Yio Chu Kang",
  "Yishun",
];
